import type { Metadata } from "next";
// import 'react-toastify/dist/ReactToastify.css';
// import { ToastContainer } from 'react-toastify';
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/header";
import { AuthProvider } from "./(user)/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en">
      <body>
      <AuthProvider>
      <div className="flex flex-col h-screen">
            <div className="flex flex-1">
              <Sidebar />
              
              <main className="flex-1 overflow-y-auto">
              <Header/>
              <div>{children}</div>
              </main>
            </div>
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
