import type { Metadata } from "next";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { AuthProvider } from "./(user)/AuthContext";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Jahiz Plus",
  description: "Generated by create next app",
};

export default async function PublicLayout({ children}: { children: React.ReactNode; }) { 
     // Extract current pathname from headers
  // const headersList = await headers();
  // const referer = headersList.get("referer") || ""; // Get full referer URL
  // const currentPath = new URL(referer, "http://localhost").pathname; // Extract pathname

  // const isLoginPage = currentPath === "/login";
  return (
    <html lang="en">
      <body>
      <AuthProvider>
      {/* <div className="flex min-h-screen">
        <ToastContainer theme='colored' position='top-center' />
      {!isLoginPage && <Sidebar />} 
      <main className={`flex-1 ${isLoginPage ? "w-full" : ""}`}>{children}</main>
      </div> */}
      
        <div className="relative flex h-screen">
          <Sidebar />    
          <main className="flex-1 overflow-y-auto transition-all duration-300">
          <ToastContainer theme='colored' position='top-center' />
          <div>{children}</div>
          </main>
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}